language: python
python:
  - "3.5.2"

services:
  - sqlite3

sudo: required
install:

  make install
  sudo apt-get install python3
  # - pip install pyTelegramBotAPI
  # - pip install -U pytest
  # -


script: make test
