language: python
python:
  - "3.5.2"

services:
  - sqlite3

sudo: required
install:

  make install
  apt-get install build-dep python-psycopg2
  pip install psycopg2
  # - pip install pyTelegramBotAPI
  # - pip install -U pytest
  # -


script: make test
