language: python
python:
  - "3.5.2"

services:
  - postgresql

sudo: required

test:
  adapter: postgresql
  database: travis_ci_test

install:
  make install
  # - pip install pyTelegramBotAPI
  # - pip install -U pytest
  # -


script: make test
